version: '3.7'

services:
  database:
    image: mysql:latest
    container_name: database
    env_file:
      - .env
    networks:
      - database_net
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
    volumes:
      - database_data:/var/lib/mysql
      - ./BDD/init-db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
  adminer:
    image: dehy/adminer
    container_name: adminer
    networks:
      - database_net
    ports:
      - 8080:80
  mysql-cron-backup:
    container_name: db-backup
    image: fradelg/mysql-cron-backup
    depends_on:
      - database
    volumes:
      - ./BDD/backup:/backup
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - database_net
networks:
  database_net:
    driver: bridge
    name: database_net
volumes:
  database_data: